seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
output_folder: /mnt/009-Audio/Internships/AccelAuthentification/training_data/trained_models/farfield_aug/20mic/CKPT+2024-08-21+18-50-30+00
save_folder: !ref <output_folder>

# "/mnt/009-Audio/Internships\AccelAuthentification/chinese_accel_micro_databases/separateAug"
base_verification_directory: "/mnt/009-Audio/Internships/AccelAuthentification/chinese_accel_micro_databases/separateAug"
is_path_abs: False

data_path: "/mnt/009-Audio/Internships/AccelAuthentification/training_data/verif_pairs/trimmed_paper_pairs/SeparateEars_babble6_4s+_1234.txt"
results_dir: '/mnt/009-Audio/Internships/AccelAuthentification/training_data/single_mod'

# Feature parameters
n_MFCC : 20




    
embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_MFCC>
    channels: [64, 64, 64, 64, 192]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    groups: [1, 1, 1, 1, 1]
    attention_channels: 64
    lin_neurons: 192

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    # paths:
    #     embedding_model: !ref <whateve>/embedding_model.ckpt


verif_config:
  feat_mode: 'Fbank'
  preprocess: True
  audio_norm : True
  WGN : False
  WGN_snr: 24


# Progress printing frequency
print_freq: 1000

